"""
Application state management for the Multimodal Agentic AI Assistant.

This module defines the data structures that hold the shared state across all
LangGraph nodes. There are three separate memory stores:
1. Shared conversation history (used by text and audio modules)
2. Image interaction memory (used by vision module)
3. Image generation memory (used by image generation module)

The ApplicationState class combines all three into a single state object that
LangGraph passes between nodes.
"""

from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class ConversationMessage:
    """
    A single message in the conversation history.
    
    Args:
        role: Either "user" or "assistant"
        content: The text content of the message
    
    Returns:
        None (this is a data class)
    """
    role: str  # "user" or "assistant"
    content: str


@dataclass
class ImageInteraction:
    """
    Record of an image that was uploaded and analyzed by the vision module.
    
    Args:
        image_path: File path to the uploaded image
        description: The text description generated by LLaVA
        timestamp: When the image was analyzed
    
    Returns:
        None (this is a data class)
    """
    image_path: str
    description: str
    timestamp: datetime


@dataclass
class GeneratedImage:
    """
    Record of an image generated by the image generation module.
    
    Args:
        prompt: The original text prompt the user provided
        file_path: Where the generated image was saved
        timestamp: When the image was generated
        metadata: Optional dict with generation parameters (e.g., model version, seed)
    
    Returns:
        None (this is a data class)
    """
    prompt: str
    file_path: str
    timestamp: datetime
    metadata: dict = field(default_factory=dict)


@dataclass
class ApplicationState:
    """
    The complete shared state passed between all LangGraph nodes.
    
    This state object is what LangGraph uses to pass data between nodes.
    Each node reads what it needs and writes its results back before returning.
    
    Args:
        mode: Currently active mode ("text", "audio", "vision", or "imagine")
        conversation_history: List of ConversationMessage objects shared by text and audio modules
        image_interactions: List of ImageInteraction objects for follow-up questions on images
        image_generations: List of GeneratedImage objects for referencing previous generations
        user_input: The current user message being processed
    
    Returns:
        None (this is a data class)
    """
    mode: str = "text"  # Default mode
    conversation_history: list[ConversationMessage] = field(default_factory=list)
    image_interactions: list[ImageInteraction] = field(default_factory=list)
    image_generations: list[GeneratedImage] = field(default_factory=list)
    user_input: str = ""  # The current message being processed
