"""
Image interaction memory manager for the vision module.

This module manages the history of images that have been uploaded and analyzed
by the vision module. It stores the image path, the description generated by
LLaVA, and the timestamp of when it was analyzed.

This memory allows users to ask follow-up questions about an image without
having to upload it again. For example, after analyzing an image, the user can
ask "What color is the box in the top left?" and the module can retrieve the
image from memory to use as context.
"""

from state import ImageInteraction
from datetime import datetime


class ImageInteractionMemory:
    """
    Manager for the history of analyzed images and their descriptions.
    
    This class stores all images that have been uploaded and analyzed during
    the session. It provides methods to add new interactions, retrieve recent
    images, and find specific interactions for follow-up questions.
    """
    
    def __init__(self, initial_interactions: list[ImageInteraction] | None = None):
        """
        Initialize the image interaction memory.
        
        Args:
            initial_interactions: Optional list of ImageInteraction objects to
                                start with. If None, starts with empty history.
        
        Returns:
            None (this is a constructor)
        """
        self.interactions = initial_interactions if initial_interactions is not None else []
    
    def add_interaction(self, image_path: str, description: str) -> None:
        """
        Add a new image interaction to the memory.
        
        Args:
            image_path: File path to the uploaded image
            description: The description generated by LLaVA
        
        Returns:
            None
        """
        interaction = ImageInteraction(
            image_path=image_path,
            description=description,
            timestamp=datetime.now()
        )
        self.interactions.append(interaction)
    
    def get_all_interactions(self) -> list[ImageInteraction]:
        """
        Get all image interactions in the memory.
        
        Args:
            None
        
        Returns:
            A list of all ImageInteraction objects in chronological order
        """
        return self.interactions
    
    def get_most_recent_interaction(self) -> ImageInteraction | None:
        """
        Get the most recently analyzed image.
        
        This is used for follow-up questions. When the user asks a follow-up
        question without specifying which image, the most recent one is assumed.
        
        Args:
            None
        
        Returns:
            The most recent ImageInteraction, or None if no interactions exist
        """
        if not self.interactions:
            return None
        return self.interactions[-1]
    
    def get_most_recent_image_path(self) -> str | None:
        """
        Get the file path of the most recently analyzed image.
        
        Convenience method for quickly retrieving just the path of the most
        recent image, without needing the full interaction object.
        
        Args:
            None
        
        Returns:
            The file path of the most recent image, or None if no interactions exist
        """
        recent = self.get_most_recent_interaction()
        return recent.image_path if recent else None
    
    def get_interaction_by_path(self, image_path: str) -> ImageInteraction | None:
        """
        Get the interaction for a specific image by its file path.
        
        Args:
            image_path: The file path to search for
        
        Returns:
            The ImageInteraction with that path, or None if not found
        """
        for interaction in reversed(self.interactions):
            if interaction.image_path == image_path:
                return interaction
        return None
    
    def get_last_n_interactions(self, n: int) -> list[ImageInteraction]:
        """
        Get the last N image interactions.
        
        Useful for providing recent context when the user references multiple
        images or when scrolling through analysis history.
        
        Args:
            n: Number of interactions to retrieve (if n > total, returns all)
        
        Returns:
            A list of the last N ImageInteraction objects
        """
        return self.interactions[-n:] if n > 0 else []
    
    def clear(self) -> None:
        """
        Clear all image interactions from memory.
        
        Use this to reset image history when starting a new session or when
        explicitly requested by the user.
        
        Args:
            None
        
        Returns:
            None
        """
        self.interactions = []
    
    def get_interaction_count(self) -> int:
        """
        Get the total number of image interactions in memory.
        
        Args:
            None
        
        Returns:
            The number of images that have been analyzed
        """
        return len(self.interactions)
