"""
Image generation memory manager for the image generation module.

This module manages the history of images that have been generated by the
image generation module. It stores the original prompt, the file path of the
generated image, and metadata like timestamp and generation parameters.

This memory allows users to reference or modify previously generated images.
For example, after generating an image, the user can say "Generate a similar
image but at night" and the module can retrieve the previous generation to use
as context for the new request.
"""

from state import GeneratedImage
from datetime import datetime


class ImageGenerationMemory:
    """
    Manager for the history of generated images and their prompts.
    
    This class stores all images that have been generated during the session,
    along with the prompts that created them and metadata about the generation.
    It provides methods to add new generations, retrieve previous ones, and
    support follow-up requests that reference earlier generations.
    """
    
    def __init__(self, initial_generations: list[GeneratedImage] | None = None):
        """
        Initialize the image generation memory.
        
        Args:
            initial_generations: Optional list of GeneratedImage objects to
                               start with. If None, starts with empty history.
        
        Returns:
            None (this is a constructor)
        """
        self.generations = initial_generations if initial_generations is not None else []
    
    def add_generation(self, prompt: str, file_path: str, metadata: dict | None = None) -> None:
        """
        Add a new generated image to the memory.
        
        Args:
            prompt: The original text prompt the user provided
            file_path: The path where the generated image was saved
            metadata: Optional dict with generation parameters (e.g., model version,
                     seed, steps). If None, an empty dict is used.
        
        Returns:
            None
        """
        generation = GeneratedImage(
            prompt=prompt,
            file_path=file_path,
            timestamp=datetime.now(),
            metadata=metadata if metadata is not None else {}
        )
        self.generations.append(generation)
    
    def get_all_generations(self) -> list[GeneratedImage]:
        """
        Get all generated images in the memory.
        
        Args:
            None
        
        Returns:
            A list of all GeneratedImage objects in chronological order
        """
        return self.generations
    
    def get_most_recent_generation(self) -> GeneratedImage | None:
        """
        Get the most recently generated image.
        
        This is used for follow-up requests. When the user asks to generate
        a variation without specifying which image, the most recent one is assumed.
        
        Args:
            None
        
        Returns:
            The most recent GeneratedImage, or None if no generations exist
        """
        if not self.generations:
            return None
        return self.generations[-1]
    
    def get_most_recent_prompt(self) -> str | None:
        """
        Get the prompt of the most recently generated image.
        
        Convenience method for quickly retrieving just the prompt of the most
        recent generation, without needing the full generation object.
        
        Args:
            None
        
        Returns:
            The prompt string of the most recent generation, or None if no generations exist
        """
        recent = self.get_most_recent_generation()
        return recent.prompt if recent else None
    
    def get_generation_by_index(self, index: int) -> GeneratedImage | None:
        """
        Get a specific generation by its index in the history.
        
        Allows the user to reference older generations by number, e.g.,
        "Modify generation 2 to have a sunset instead".
        
        Args:
            index: The position in the history (0 = first generation, -1 = most recent)
        
        Returns:
            The GeneratedImage at that index, or None if index is out of bounds
        """
        try:
            return self.generations[index]
        except IndexError:
            return None
    
    def get_last_n_generations(self, n: int) -> list[GeneratedImage]:
        """
        Get the last N generated images.
        
        Useful for providing recent context when the user wants to see recent
        generations or compare variations.
        
        Args:
            n: Number of generations to retrieve (if n > total, returns all)
        
        Returns:
            A list of the last N GeneratedImage objects in chronological order
        """
        return self.generations[-n:] if n > 0 else []
    
    def clear(self) -> None:
        """
        Clear all generated image history from memory.
        
        Use this to reset generation history when starting a new session or
        when explicitly requested by the user.
        
        Args:
            None
        
        Returns:
            None
        """
        self.generations = []
    
    def get_generation_count(self) -> int:
        """
        Get the total number of images that have been generated.
        
        Args:
            None
        
        Returns:
            The number of images generated during this session
        """
        return len(self.generations)
